### ISSUE TITLE
Keys of 'connects_to' are String when json is parsed

### ISSUE THREAD

**Issue by luizcarlos1405** [LittleMouseGames/whiskers#10]
**Godot version:**
3.1 beta 3

**OS/device including version:**
Linux Ubuntu 18.04

**Issue description:**
The key 'connects_to' of a Node data is a dictionary and, because of that, when an exported JSON file is parsed the keys of this dictionary are set to String and not int. Is this intentional? To me, it looks like they would be better as integers on an array and maybe even starting at 0 and not 1.

Looks like it is a [JSON problem](https://stackoverflow.com/questions/7811842/can-json-object-attribute-names-be-integers)

Edit:
On Dialogue.gd at the method `populate` these keys are accessed with an integer. But when a parsed JSON is given this code needs a lot of `as String` casts. 

**Steps to reproduce:**
`typeof(parsed_json_export['Start']['connects_to'].keys()[0])`

**Comment by yochrisbolton** [comment]
This is not intentional, and will be addressed in the v.1.2 update. Cheers :beers:
