### ISSUE TITLE
Graph nodes allow clicks to go through them

### ISSUE THREAD

**Issue by Awkor** [LittleMouseGames/whiskers#4]
**Godot version:**
Godot 3.1 beta 3

**OS/device including version:**
Microsoft Windows 10 Pro 10.0.17134 Build 17134

**Issue description:**
When two nodes overlap, it's possible to start a connection from the bottom node, even if it's connection slot is hidden by the top node.

**Steps to reproduce:**
![](https://giant.gfycat.com/ShowyUniformCuscus.gif)

**Minimal reproduction project:**
A graph with at least 2 nodes.

**Comment by yochrisbolton** [comment]
This seens to be an issue with the GraphNode system its self, but there *appears* to be a possible workaround! I'm investigating. 

Thank you!
